# Generated by Django 5.0.2 on 2024-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcap_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfile', models.FileField(upload_to='')),
            ],
        ),
    ]
