# Generated by Django 5.0.2 on 2024-05-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pcap_file_pfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pcap_file',
        ),
    ]
