-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cvemetadata
(
    cveid integer NOT NULL,
    state text COLLATE pg_catalog."default",
    assignershortname text COLLATE pg_catalog."default",
    datereserved text COLLATE pg_catalog."default",
    datepublished text COLLATE pg_catalog."default",
    dateupdated text COLLATE pg_catalog."default",
    CONSTRAINT cvemetadata_pkey PRIMARY KEY (cveid)
);

CREATE TABLE IF NOT EXISTS public.vulnerabilities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cveid integer,
    dateupdated text COLLATE pg_catalog."default",
    vendor text COLLATE pg_catalog."default",
    product text COLLATE pg_catalog."default",
    versions text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    reference integer,
    confidentialityimpact text COLLATE pg_catalog."default",
    integrityimpact text COLLATE pg_catalog."default",
    availabilityimpact text COLLATE pg_catalog."default",
    basescore integer,
    baseseverity text COLLATE pg_catalog."default",
    CONSTRAINT vulnerabilities_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.vulnerabilities
    ADD CONSTRAINT fk_vulnerabilities_cvemetadata FOREIGN KEY (cveid)
    REFERENCES public.cvemetadata (cveid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;